version: "3.7"

services:
  iperf:
    image: clearlinux/iperf
    #ports:
    #  - target: 5201
    #  - published: 5201
    #  - protocol: tcp
    #  - mode: host
    command: >
      iperf3 -s
    networks:
      - traefik_public
    deploy:
      labels:
        # traefik common
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv2
        - "traefik.tcp.routers.iperf.rule=HostSNI(`*`)"
        - "traefik.tcp.services.iperf.loadbalancer.server.port=5201"
        - "traefik.tcp.routers.iperf.entrypoints=iperf"

networks:
  traefik_public:
    external: true