version: "3.7"

services:
  iperf:
    image: clearlinux/iperf
    #ports:
    #  - target: 5201
    #  - published: 5201
    #  - protocol: tcp
    #  - mode: host
    networks:
      - traefik_public
    deploy:
      labels:
        # traefik common
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv2
        - "traefik.http.routers.iperf.rule=Host(`iperf.ecom.com.ar`)"
        - "traefik.http.services.iperf.loadbalancer.server.port=5201"

networks:
  traefik_public:
    external: true