version: "3.7"

services:
  iperf:
    image: clearlinux/iperf
    ports:
      - 5201:5201
    command: >
      iperf3 -s
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true