version: "3.7"

services:
  iperf:
    image: clearlinux/iperf
    ports:
      - target: 5201
        published: 5201
        protocol: tcp
        mode: host
    command: >
      iperf3 -s
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true